databases:
  - name: micronauts
    databaseName: micronauts_jcvy
    user: micronauts_jcvy_user

services:
  - type: web
    name: recipe_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronauts
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false